#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DirSearchClient_Android.Resource", IsApplication=true)]

namespace DirSearchClient_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::DirSearchClient_Android.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::DirSearchClient_Android.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::DirSearchClient_Android.Resource.String.ApplicationName;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050010
			public const int agentWebView = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int givenLabel = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int givenResult = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout2 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout3 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout4 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int phoneLabel = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int phoneResult = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int searchButton = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int searchTermText = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int statusResult = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int surnameLabel = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int surnameResult = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int upnLabel = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int upnResult = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int WebAuthenticationBroker = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int EmptyString = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int InvalidSearch = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int Success = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int UserNotFound = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
